### Author: Frish2021 ###
name: Docs CI

on:
  push:
    paths:
      - "*.md"
      - "pnpm-lock.yaml"
      - "package.json"
      - '.github/workflows/deploy_docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
        working-directory: ./docs

      - name: Build project
        run: pnpm build
        working-directory: ./docs

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
